"""Pydantic request/response schemas. Re-exported for backward compatibility."""

from src.schemas.auth import (
    LoginRequest,
    ResendVerificationRequest,
    ResendVerificationResponse,
    SignupRequest,
    SignupResponse,
    TokenResponse,
    VerifyEmailRequest,
    VerifyEmailResponse,
)
from src.schemas.bio import BioCreateUpdate, BioResponse, PastCompanyItem
from src.schemas.builder import (
    BuilderSessionCommitResponse,
    BuilderTranscriptCommitRequest,
    CardFamilyResponse,
    ChildValueItem,
    CommitCardDraftChild,
    CommitCardDraftRequest,
    ExperienceCardChildPatch,
    ExperienceCardChildResponse,
    ExperienceCardCreate,
    ExperienceCardPatch,
    ExperienceCardResponse,
    FillFromTextRequest,
    FillFromTextResponse,
    FinalizeExperienceCardRequest,
)
from src.schemas.chat import (
    ConversationDetail,
    ConversationPeer,
    ConversationSummary,
    MessageItem,
    SendMessageRequest,
    StartChatRequest,
    StartChatResponse,
)
from src.schemas.contact import ContactDetailsResponse, PatchContactRequest
from src.schemas.credits import CreditsResponse, LedgerEntryResponse, PurchaseCreditsRequest
from src.schemas.discover import (
    PersonListItem,
    PersonListResponse,
    PersonPublicProfileResponse,
    UnlockedCardItem,
    UnlockedCardsResponse,
)
from src.schemas.profile import (
    PatchProfileRequest,
    PatchVisibilityRequest,
    PersonResponse,
    VisibilitySettingsResponse,
)
from src.schemas.search import (
    PersonProfileResponse,
    PersonSearchResult,
    SavedSearchesResponse,
    SavedSearchItem,
    SearchRequest,
    SearchResponse,
    UnlockContactRequest,
    UnlockContactResponse,
)

__all__ = [
    "SignupRequest",
    "SignupResponse",
    "LoginRequest",
    "TokenResponse",
    "VerifyEmailRequest",
    "VerifyEmailResponse",
    "ResendVerificationRequest",
    "ResendVerificationResponse",
    "PersonResponse",
    "PatchProfileRequest",
    "VisibilitySettingsResponse",
    "PatchVisibilityRequest",
    "PastCompanyItem",
    "BioResponse",
    "BioCreateUpdate",
    "ContactDetailsResponse",
    "PatchContactRequest",
    "CreditsResponse",
    "PurchaseCreditsRequest",
    "LedgerEntryResponse",
    "FillFromTextRequest",
    "FillFromTextResponse",
    "BuilderSessionCommitResponse",
    "BuilderTranscriptCommitRequest",
    "FinalizeExperienceCardRequest",
    "ExperienceCardCreate",
    "ExperienceCardPatch",
    "ExperienceCardResponse",
    "ExperienceCardChildPatch",
    "ExperienceCardChildResponse",
    "ChildValueItem",
    "CardFamilyResponse",
    "CommitCardDraftRequest",
    "CommitCardDraftChild",
    "SearchRequest",
    "PersonSearchResult",
    "SearchResponse",
    "PersonProfileResponse",
    "SavedSearchItem",
    "SavedSearchesResponse",
    "UnlockContactRequest",
    "UnlockContactResponse",
    "PersonListItem",
    "PersonListResponse",
    "PersonPublicProfileResponse",
    "UnlockedCardItem",
    "UnlockedCardsResponse",
    "StartChatRequest",
    "StartChatResponse",
    "MessageItem",
    "ConversationPeer",
    "ConversationSummary",
    "ConversationDetail",
    "SendMessageRequest",
]
