"""Pydantic request/response schemas. Re-exported for backward compatibility."""

from src.schemas.auth import (
    SignupRequest,
    SignupResponse,
    LoginRequest,
    TokenResponse,
    VerifyEmailRequest,
    VerifyEmailResponse,
    ResendVerificationRequest,
    ResendVerificationResponse,
)
from src.schemas.profile import (
    PersonResponse,
    PatchProfileRequest,
    VisibilitySettingsResponse,
    PatchVisibilityRequest,
)
from src.schemas.bio import PastCompanyItem, BioResponse, BioCreateUpdate
from src.schemas.contact import ContactDetailsResponse, PatchContactRequest
from src.schemas.credits import CreditsResponse, PurchaseCreditsRequest, LedgerEntryResponse
from src.schemas.builder import (
    FillFromTextRequest,
    FillFromTextResponse,
    BuilderChatTurnRequest,
    BuilderChatTurnResponse,
    BuilderSessionResponse,
    BuilderSessionCommitResponse,
    BuilderTranscriptCommitRequest,
    BuilderTurnResponse,
    CommitDraftSetRequest,
    FinalizeExperienceCardRequest,
    ExperienceCardCreate,
    ExperienceCardPatch,
    ExperienceCardResponse,
    ExperienceCardChildPatch,
    ExperienceCardChildResponse,
    ChildValueItem,
    CardFamilyResponse,
)
from src.schemas.search import (
    SearchRequest,
    PersonSearchResult,
    SearchResponse,
    PersonProfileResponse,
    SavedSearchItem,
    SavedSearchesResponse,
    UnlockContactRequest,
    UnlockContactResponse,
)
from src.schemas.discover import (
    PersonListItem,
    PersonListResponse,
    PersonPublicProfileResponse,
    UnlockedCardItem,
    UnlockedCardsResponse,
)
from src.schemas.chat import (
    StartChatRequest,
    StartChatResponse,
    MessageItem,
    ConversationPeer,
    ConversationSummary,
    ConversationDetail,
    SendMessageRequest,
)

__all__ = [
    "SignupRequest",
    "SignupResponse",
    "LoginRequest",
    "TokenResponse",
    "VerifyEmailRequest",
    "VerifyEmailResponse",
    "ResendVerificationRequest",
    "ResendVerificationResponse",
    "PersonResponse",
    "PatchProfileRequest",
    "VisibilitySettingsResponse",
    "PatchVisibilityRequest",
    "PastCompanyItem",
    "BioResponse",
    "BioCreateUpdate",
    "ContactDetailsResponse",
    "PatchContactRequest",
    "CreditsResponse",
    "PurchaseCreditsRequest",
    "LedgerEntryResponse",
    "FillFromTextRequest",
    "FillFromTextResponse",
    "BuilderChatTurnRequest",
    "BuilderChatTurnResponse",
    "BuilderSessionResponse",
    "BuilderSessionCommitResponse",
    "BuilderTranscriptCommitRequest",
    "BuilderTurnResponse",
    "CommitDraftSetRequest",
    "FinalizeExperienceCardRequest",
    "ExperienceCardCreate",
    "ExperienceCardPatch",
    "ExperienceCardResponse",
    "ExperienceCardChildPatch",
    "ExperienceCardChildResponse",
    "ChildValueItem",
    "CardFamilyResponse",
    "SearchRequest",
    "PersonSearchResult",
    "SearchResponse",
    "PersonProfileResponse",
    "SavedSearchItem",
    "SavedSearchesResponse",
    "UnlockContactRequest",
    "UnlockContactResponse",
    "PersonListItem",
    "PersonListResponse",
    "PersonPublicProfileResponse",
    "UnlockedCardItem",
    "UnlockedCardsResponse",
    "StartChatRequest",
    "StartChatResponse",
    "MessageItem",
    "ConversationPeer",
    "ConversationSummary",
    "ConversationDetail",
    "SendMessageRequest",
]
